name: Build OC4VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install p7zip

      - name: Build OC4VM
        run: ./make.sh

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oc4vm-release
          path: dist/
          if-no-files-found: error
